apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cluster-pipeline
  namespace: ci
spec:
  params:
  - name: repo_url
  - name: revision
  workspaces:
  - name: source
  - name: basic-auth
  tasks:
  - name: github-add-comment
    taskRef:
      name: github-add-comment
    params:
      - name: REQUEST_URL
        value: "{{ repo_url }}/pull/{{ pull_request_number }}"
      - name: COMMENT_OR_FILE
        value: "Pipelines as Code IS GREAT FROM Cluster!"
      - name: GITHUB_TOKEN_SECRET_NAME
        value: "{{ git_auth_secret }}"
      - name: GITHUB_TOKEN_SECRET_KEY
        value: "git-provider-token"
  - name: fetch-repository
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
      - name: output
        workspace: source
      - name: basic-auth
        workspace: basic-auth
    params:
      - name: url
        value: $(params.repo_url)
      - name: revision
        value: $(params.revision)
  - name: noop-task
    runAfter:
      - fetch-repository
    workspaces:
      - name: source
        workspace: source
    taskSpec:
      workspaces:
        - name: source
      steps:
        - name: noop-task
          image: registry.access.redhat.com/ubi9/ubi-micro
          workingDir: $(workspaces.source.path)
          script: |
            exit 0
